update rw_visual.py
Hope I'm doing this right.
 
point_numbers = list(range(rw.num_points + 1))  ... to avoid the following error:

Traceback (most recent call last):
  File "C:\Users\mbrad\GitHub\lib\site-packages\matplotlib\colors.py", line 158, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
KeyError: (0, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mbrad\GitHub\lib\site-packages\matplotlib\axes\_axes.py", line 4210, in scatter
    colors = mcolors.to_rgba_array(c)
  File "C:\Users\mbrad\GitHub\lib\site-packages\matplotlib\colors.py", line 259, in to_rgba_array
    result[i] = to_rgba(cc, alpha)
  File "C:\Users\mbrad\GitHub\lib\site-packages\matplotlib\colors.py", line 160, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "C:\Users\mbrad\GitHub\lib\site-packages\matplotlib\colors.py", line 211, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/mbrad/PycharmProjects/GitHub/Data-Vizualization/Random Walk Patern Generator/rw_generator.py", line 37, in <module>
    edgecolor='none', s=1)
  File "C:\Users\mbrad\GitHub\lib\site-packages\matplotlib\pyplot.py", line 2793, in scatter
    verts=verts, edgecolors=edgecolors, data=data, **kwargs)
  File "C:\Users\mbrad\GitHub\lib\site-packages\matplotlib\__init__.py", line 1785, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\mbrad\GitHub\lib\site-packages\matplotlib\axes\_axes.py", line 4223, in scatter
    .format(nc=n_elem, xs=x.size, ys=y.size)
ValueError: 'c' argument has 50000 elements, which is not acceptable for use with 'x' with size 50001, 'y' with size 50001.


Amazing book.
Thanks